### ISSUE TITLE
ERROR - could not run node: preproc.initialization.petVolume.a0

### ISSUE THREAD

**Issue by guilhermepovala** [APPIAN-PET/APPIAN#15]
Hi,

When I try to run the example in the User Guide **Default: Coregistration + MRI Preprocessing + Results Report**, after some processing using the default settings, an error occurs: **could not run node: preproc.initialization.petVolume.a0**

Any tips on how to solve it?

**Comment by tfunck** [comment]
Hi, 

Could you attach the output that is printed when you try to run APPIAN? I'll rerun the example now and see if I can reproduce the same error. 

Thanks a lot for taking the time to post a bug report! 

Thomas

**Comment by tfunck** [comment]
Two possible solutions : 
1) In the user guide, there was a "find" command to fix the cimbi data. This command didn't work quite right, so I've replaced it with the following : 

find -iregex '.*\.\(json\|mnc\|nii\|nii.gz\)$'   -exec sh -c 'x="{}"; f2=`echo $x | sed 's/ses_/ses-/g'`;  mv $x $f2  ' \;

2) We had made some bug fixes but had only pushed them to appian:latest-dev. I've now pushed them to appian:latest. So you can try to pull from tffunck/appian:latest again. 

Let me know if either works, or if you're still running into problems. 

Thomas

**Comment by guilhermepovala** [comment]
Hey Thomas,

All working fine now.

The find command I had already fixed. The second solution solved my problem!

Off-topic: using nifti files I don't need to create the json?

**Comment by tfunck** [comment]
Great, glad to hear it! 

In theory, according to the BIDS standard the nifti files should be accompanied by a json header, so there is no need to create one. Json headers are only created by APPIAN when MINC input files are being used. While MINC files do have their own internal headers, they are tough to work with and don't conform to the BIDS specification, so it's easier if all header information is stored in the same in a json file regardless the input file type. 

Don't hestiate to post any more bugs, issues, or questions you may have! 

Thomas
