### ISSUE TITLE
Add Zenodo DOI 

### ISSUE THREAD

**Issue by gkiar** [APPIAN-PET/APPIAN#21]
Hey!

I was bouncing around to try and remember the status of the Boutiques descriptor for this project, and realized that there's no DOI for citing the actual APPIAN codebase! These are super easy to obtain through Zenodo as you probably know, and make it easy to differentiate between version of software when citing (esp. useful for before/after bug fixes), and giving new devs co-authorship automatically w/out a new in-press publication.

There's the official guide for how to do it, here: https://guides.github.com/activities/citable-code/

I'd recommend taking the 5-10 min to set it up sooner than later, so that it'll be there moving forward :) Happy to help/chat/or even do it if you wanted to give me temporary access to the APPIAN org that I'd give back when finished the integration.

Once that's done, I'll circle back on the Boutiques stuff ;)

cc: @tfunck @llevitis @pjtoussaint

**Comment by llevitis** [comment]
Done! 🎉
